### ISSUE TITLE
Option to set start time of logs

### ISSUE THREAD

**Issue by inoyakaigor** [andrea-falco/lens-multi-pod-logs#11]
![image](https://github.com/andrea-falco/lens-multi-pod-logs/assets/1235286/835e0583-a987-4573-928b-8d0c81fe8d4f)
Currently logs started since a second before. My typical use case is checking logs after something goes wrong and this «after» often is more earlier rather than 1 second

**Comment by inoyakaigor** [comment]
Also it is not looks like rocket science to add the option and I can make a PR but I don't know how to test it

**Comment by andrea-falco** [comment]
Hi @inoyakaigor, I have just released a new version (v0.3.6) which includes a new preference for since duration.
The preference will set the --since flag on stern command.

You can see below a screenshot of the new preferences:

![since-preference](https://github.com/andrea-falco/lens-multi-pod-logs/assets/23004377/d86cada1-b917-4acc-9d8c-643e3d10973a)
